# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffbe4e8e4bae9788314a0f241b3b267f778fef83f0c6f3866c17c05987cd3cd8cb3366ea45e5a9be02cbc9056fae159257d82a45f246f3298b44008056025e2

test:
  secret_key_base: c44a451c1a32dba5c9f66ff6ab21ed7b2366fa213c15e284ac2f9b623c828882b0aaf2b0d7882e541e412de8d0bc08aef8942450a371cbd088e209e07e8ed318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
